import { StyleSheet } from "react-native";
import colors from "../../../utils/colors";

export const styles = StyleSheet.create({
  container: {
    display: "flex",
    width: "100%",
    flexDirection: "column",
    alignItems: "center",
    backgroundColor: colors.white,
    padding: 12,
    paddingTop: 24,
    marginBottom: 16,
  },
  titleDiv: {
    display: "flex",
    width: "100%",
    flexDirection: "row",
    alignItems: "flex-start",
  },
  title: {
    alignSelf: "auto",
    backgroundColor: colors.white,
    marginTop: -12,
    fontWeight: "500",
    borderWidth: 1,
    borderRadius: 15,
    borderColor: colors.purple,
    color: colors.purple,
    padding: 8,
  },
  divisor: {
    flex: 1,
    borderTopWidth: 1,
    borderRadius: 15,
    borderColor: colors.dark,
    marginRight: 6,
  },
  card: {
    display: "flex",
    width: "100%",
    flexDirection: "column",
    justifyContent: "flex-start",
    paddingTop: 0,
    paddingHorizontal: 0,
    paddingBottom: 16,
    gap: 24,
    borderWidth: 1,
    borderRadius: 15,
    borderColor: colors.dark,
    elevation: 5,
    shadowColor: colors.black,
    backgroundColor: colors.white,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
  },
  description: {
    textAlign: "left",
    margin: 12,
    marginTop: 0,
    marginHorizontal: 16,
  },
  medicines: {
    backgroundColor: colors.dark,
    marginTop: 0,
    marginHorizontal: 16,
  },
  medicinesText: {
    fontWeight: "500",
    margin: 12,
    marginBottom: 0,
    marginHorizontal: 16,
    gap: 8,
    color: colors.darkest,
  },
});
